version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - sudo apt update && apt upgrade -y
      - sudo apt install python3-pip python3-dev -y
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check
      - pip install -r requirements.txt
      - sudo apt install ufw
      
  pre_build:
    commands:
     - sudo add-apt-repository ppa:ubuntugis/ppa
     - sudo apt-get update
     - sudo apt-get install gdal-bin -y
     - systemctl restart nginx.service
     - ogrinfo --version
     - gdalinfo --version
     - sudo apt update
     - sudo apt -y upgrade
     - systemctl restart unattended-upgrades.service
     - sudo apt-get install libgdal-dev
     - export CPLUS_INCLUDE_PATH=/usr/include/gdal
     - export C_INCLUDE_PATH=/usr/include/gdal
     - pip install GDAL
     - sudo apt -y install gnupg2
     - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
     - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
     - sudo apt install postgis postgresql-14-postgis-3 -y
    

    commands:
      - echo "Running Django migrations"
      - python manage.py makemigrations
      - python manage.py migrate --traceback
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput  >/dev/null
      - echo "Build Stage Successful."
artifacts:
  files:
    - '**/*'