# Generated by Django 3.2.5 on 2023-04-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pin_code',
            new_name='eir_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
